### ISSUE TITLE
DEFINE no struct.h

### ISSUE THREAD

**Issue by joaotassoni** [dfantonio/UFRGS-INF01202#7]
No enunciado do trabalho, página 6, é pedido que o tamanho do estoque, descarte, fundação e tableau sejam especificados através de define.

**Comment by dfantonio** [comment]
Bah, vai ficar feião kkkkk

**Comment by dfantonio** [comment]
Vai na fé filhão e aprova o [MR](https://github.com/dfantonio/UFRGS-INF01202/pull/9/files) kkkkkkk
